# Generated by Django 5.1.6 on 2025-11-07 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
