# Generated by Django 5.1.6 on 2026-04-07 03:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_message_thread_starter'),
        ('interactions', '0003_alter_favorite_create_date'),
        ('songs', '0053_alter_songstats_average_comment_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('pending_screening', models.BooleanField(default=True)),
                ('rejection_text', models.TextField(blank=True, max_length=500, null=True)),
                ('impression_score', models.PositiveSmallIntegerField(default=0)),
                ('impression_text', models.TextField(blank=True, max_length=11000, null=True)),
                ('technique_score', models.PositiveSmallIntegerField(default=0)),
                ('technique_text', models.TextField(blank=True, max_length=3500, null=True)),
                ('development_score', models.PositiveSmallIntegerField(default=0)),
                ('development_text', models.TextField(blank=True, max_length=3000, null=True)),
                ('creativity_score', models.PositiveSmallIntegerField(default=0)),
                ('creativity_text', models.TextField(blank=True, max_length=3000, null=True)),
                ('enjoyment_score', models.PositiveSmallIntegerField(default=0)),
                ('enjoyment_text', models.TextField(blank=True, max_length=1500, null=True)),
                ('additional_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('incomplete', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.profile')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
        ),
    ]
