# Generated by Django 4.0.1 on 2022-01-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=120)),
                ('song_title', models.CharField(max_length=120)),
                ('format', models.CharField(choices=[('MOD', 'Protracker'), ('S3M', 'Scream Tracker 3'), ('XM', 'FastTracker 2'), ('IT', 'Impulse Tracker')], max_length=6)),
                ('file_size', models.PositiveIntegerField()),
                ('channels', models.PositiveSmallIntegerField()),
                ('instrument_text', models.TextField(max_length=64000)),
                ('comment_text', models.TextField(max_length=64000)),
                ('hash', models.CharField(max_length=33)),
                ('pattern_hash', models.CharField(max_length=16)),
                ('license', models.CharField(choices=[('publicdomain', 'Public Domain'), ('by-nc', 'Non-commercial'), ('by-nc-nd', 'Non-commercial No Derivatives'), ('by-nc-sa', 'Non-commercial Share Alike'), ('by-nd', 'No Derivatives'), ('by-sa', 'Share Alike'), ('by', 'Attribution'), ('cc0', 'CC0')], max_length=16)),
                ('hits', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
