# Generated by Django 4.0.1 on 2022-01-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='legacy_id',
            field=models.IntegerField(null=True),
        ),
    ]
