# Generated by Django 4.0.1 on 2022-01-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_legacy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='clean_title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
