# Generated by Django 4.0.1 on 2022-02-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_rename_song_title_song_title_song_clean_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='clean_title',
            field=models.CharField(db_index=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='filename',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='song',
            name='format',
            field=models.CharField(choices=[('MOD', 'Protracker'), ('S3M', 'Scream Tracker 3'), ('XM', 'FastTracker 2'), ('IT', 'Impulse Tracker')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='song',
            name='legacy_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
