# Generated by Django 4.0.1 on 2022-02-12 04:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_alter_song_clean_title_alter_song_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='song',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='songs_song_search__6a6723_gin'),
        ),
    ]
