# Generated by Django 4.0.1 on 2022-03-08 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_search_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongStats',
            fields=[
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='songs.song')),
                ('downloads', models.IntegerField(default=0)),
                ('total_comments', models.PositiveSmallIntegerField(default=0)),
                ('average_comment_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveSmallIntegerField(default=0)),
                ('average_review_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
    ]
