# Generated by Django 4.0.1 on 2022-03-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_songstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='hits',
        ),
        migrations.AlterField(
            model_name='songstats',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
