# Generated by Django 4.0.1 on 2022-07-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='format',
            field=models.CharField(choices=[('669', '669: Composer 669 / UNIS 669'), ('AHX', "AHX: Abyss' Highest eXperience, formerly THX"), ('AMF', 'AMF: ASYLUM / DSMI'), ('AMS', "AMS: Extreme's Tracker / Velvet Studio"), ('C67', 'C67: CDFM / Composer 670'), ('DBM', 'DBM: Digi Booster Pro'), ('DIGI', 'DIGI: Digi Booster'), ('DMF', 'DMF: X-Tracker'), ('DSM', 'DSM: DSIK'), ('DSYM', 'DSYM: Digital Symphony'), ('DTM', 'DTM: Digital Tracker / Digital Home Studio'), ('FAR', 'FAR: Farandole Composer'), ('FMT', 'FMT: FM Tracker'), ('GDM', 'GDM: BWSB Sound System'), ('HVL', 'HVL: HivelyTracker'), ('IMF', 'IMF: Imago Orpheus'), ('IT', 'IT: Impulse Tracker'), ('J2B', 'J2B: Galaxy Sound System'), ('MED', 'MED: Octamed'), ('MDL', 'MDL: Digitrakker'), ('MO3', 'MO3: Compressed Module'), ('MOD', 'MOD: Protracker, Generic MOD'), ('MPTM', 'MPTM: OpenMPT'), ('MT2', 'MT2: MadTracker 2'), ('MTM', 'MTM: Multi Tracker'), ('OKT', 'OKT: Oktalyzer'), ('PLM', 'PLM: Disorder Tracker 2'), ('PSM', 'PSM: Epic MegaGames MASI'), ('PTM', 'PTM: PolyTracker'), ('S3M', 'S3M: Scream Tracker 3'), ('SFX', 'SFX: SoundFX / MultiMedia Sound'), ('STM', 'STM: Scream Tracker'), ('STP', 'STP: SoundTracker Pro II'), ('STX', 'STX: Scream Tracker Music Interface Kit'), ('SymMOD', 'SymMOD: Symphonie / Symphonie Pro'), ('ULT', 'ULT: UltraTracker'), ('UMX', 'UMX: Unreal Music'), ('XM', 'XM: FastTracker 2')], db_index=True, max_length=6),
        ),
    ]
