# Generated by Django 4.0.1 on 2022-07-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_alter_song_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='comment_text',
            field=models.TextField(blank=True, max_length=64000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='instrument_text',
            field=models.TextField(blank=True, max_length=64000, null=True),
        ),
    ]
