# Generated by Django 4.0.1 on 2022-07-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_alter_song_comment_text_alter_song_instrument_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
