# Generated by Django 4.0.1 on 2022-07-01 23:30

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_alter_song_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
