# Generated by Django 4.0.1 on 2022-07-22 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_profile_blurb'),
        ('songs', '0015_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.profile'),
        ),
    ]
