# Generated by Django 4.0.1 on 2022-08-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_profile_blurb'),
        ('songs', '0016_alter_favorite_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('profile', 'song')},
        ),
    ]
