# Generated by Django 4.0.1 on 2022-08-10 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_news_create_date_news_update_date'),
        ('songs', '0017_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.profile')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'verbose_name_plural': 'artist comments',
                'db_table': 'artist_comments',
                'unique_together': {('profile', 'song')},
            },
        ),
    ]
