# Generated by Django 4.0.1 on 2022-08-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0018_artistcomment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artistcomment',
            table='songs_artist_comments',
        ),
    ]
