# Generated by Django 4.0.1 on 2022-09-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0019_alter_artistcomment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('group', models.CharField(choices=[('Electronica', 'Electronica'), ('Demo', 'Demo, Tracking Scene'), ('Alternative', 'Alternative'), ('Jazz', 'Jazz, Blues'), ('Other', 'Other'), ('Seasonal', 'Seasonal'), ('Pop', 'Pop, Rock'), ('Hip-Hop', 'Urban, Hip-Hop')], max_length=80)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
