# Generated by Django 4.0.1 on 2022-09-16 03:48

from django.db import migrations

def create_genres(apps, schema_editor):
    Genre = apps.get_model('songs', 'Genre')
    Genre.objects.create(name='Electronic - Techno', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Dance', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Ambient', group='Electronica', count=0)
    Genre.objects.create(name='Trance - General', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Other', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - General', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Drum & Bass', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - House', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Rave', group='Electronica', count=0)
    Genre.objects.create(name='Trance - Dream', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Breakbeat', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Industrial', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Hardcore', group='Electronica', count=0)
    Genre.objects.create(name='Chillout', group='Electronica', count=0)
    Genre.objects.create(name='Trance - Goa', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Jungle', group='Electronica', count=0)
    Genre.objects.create(name='Trance - Acid', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - IDM', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Progressive', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Gabber', group='Electronica', count=0)
    Genre.objects.create(name='Electronic - Minimal', group='Electronica', count=0)
    Genre.objects.create(name='Trance - Hard', group='Electronica', count=0)
    Genre.objects.create(name='Trance - Progressive', group='Electronica', count=0)
    Genre.objects.create(name='Trance - Tribal', group='Electronica', count=0)

    Genre.objects.create(name='Chiptune', group='Demo', count=0)
    Genre.objects.create(name='Demostyle', group='Demo', count=0)
    Genre.objects.create(name='One-Hour Compo', group='Demo', count=0)

    Genre.objects.create(name='Pop - General', group='Pop', count=0)
    Genre.objects.create(name='Pop - Synth', group='Pop', count=0)
    Genre.objects.create(name='Pop - Soft', group='Pop', count=0)
    Genre.objects.create(name='Rock - General', group='Pop', count=0)
    Genre.objects.create(name='Rock - Soft', group='Pop', count=0)
    Genre.objects.create(name='Rock - Hard', group='Pop', count=0)
    Genre.objects.create(name='Funk', group='Pop', count=0)
    Genre.objects.create(name='Disco', group='Pop', count=0)
    Genre.objects.create(name='Ballad', group='Pop', count=0)
    Genre.objects.create(name='Easy Listening', group='Pop', count=0)

    Genre.objects.create(name='Video Game', group='Other', count=0)
    Genre.objects.create(name='Orchestral', group='Other', count=0)
    Genre.objects.create(name='Classical', group='Other', count=0)
    Genre.objects.create(name='Piano', group='Other', count=0)
    Genre.objects.create(name='Fantasy', group='Other', count=0)
    Genre.objects.create(name='Soundtrack', group='Other', count=0)
    Genre.objects.create(name='Comedy', group='Other', count=0)
    Genre.objects.create(name='Medieval', group='Other', count=0)
    Genre.objects.create(name='Spiritual', group='Other', count=0)
    Genre.objects.create(name='Religious', group='Other', count=0)
    Genre.objects.create(name='Experimental', group='Other', count=0)
    Genre.objects.create(name='New Age', group='Other', count=0)
    Genre.objects.create(name='Folk', group='Other', count=0)
    Genre.objects.create(name='Country', group='Other', count=0)
    Genre.objects.create(name='Bluegrass', group='Other', count=0)
    Genre.objects.create(name='World', group='Other', count=0)
    Genre.objects.create(name='Fusion', group='Other', count=0)
    Genre.objects.create(name='Vocal Montage', group='Other', count=0)
    Genre.objects.create(name='Other', group='Other', count=0)

    Genre.objects.create(name='Alternative', group='Alternative', count=0)
    Genre.objects.create(name='Gothic', group='Alternative', count=0)
    Genre.objects.create(name='Punk', group='Alternative', count=0)
    Genre.objects.create(name='Metal - General', group='Alternative', count=0)
    Genre.objects.create(name='Metal - Extreme', group='Alternative', count=0)
    Genre.objects.create(name='Grunge', group='Alternative', count=0)

    Genre.objects.create(name='Jazz - General', group='Jazz', count=0)
    Genre.objects.create(name='Jazz - Modern', group='Jazz', count=0)
    Genre.objects.create(name='Jazz - Acid', group='Jazz', count=0)
    Genre.objects.create(name='Blues', group='Jazz', count=0)
    Genre.objects.create(name='Swing', group='Jazz', count=0)
    Genre.objects.create(name='Big Band', group='Jazz', count=0)

    Genre.objects.create(name='Hip-Hop', group='Hip-Hop', count=0)
    Genre.objects.create(name='Reggae', group='Hip-Hop', count=0)
    Genre.objects.create(name='R&B', group='Hip-Hop', count=0)
    Genre.objects.create(name='Soul', group='Hip-Hop', count=0)
    Genre.objects.create(name='Ska', group='Hip-Hop', count=0)

    Genre.objects.create(name='Christmas', group='Seasonal', count=0)
    Genre.objects.create(name='Halloween', group='Seasonal', count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0020_genre'),
    ]

    operations = [
        migrations.RunPython(create_genres)
    ]
