# Generated by Django 4.0.1 on 2022-10-13 03:07

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0022_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='text_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='title_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
