# Generated by Django 4.0.1 on 2022-10-25 21:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0023_song_text_vector_song_title_vector'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='songs_song_search__6a6723_gin',
        ),
        migrations.RemoveField(
            model_name='song',
            name='text_vector',
        ),
        migrations.AddField(
            model_name='song',
            name='comment_text_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='instrument_text_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='song',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_vector', 'instrument_text_vector', 'comment_text_vector'], name='songs_song_title_v_a4b806_gin'),
        ),
    ]
