# Generated by Django 4.0.1 on 2022-11-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0025_alter_song_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Electronic - Techno'), (2, 'Electronic - Dance'), (3, 'Electronic - Ambient'), (4, 'Trance - General'), (5, 'Electronic - Other'), (6, 'Electronic - General'), (7, 'Electronic - Drum & Bass'), (8, 'Electronic - House'), (9, 'Electronic - Rave'), (10, 'Trance - Dream'), (11, 'Electronic - Breakbeat'), (12, 'Electronic - Industrial'), (13, 'Electronic - Hardcore'), (14, 'Chillout'), (15, 'Trance - Goa'), (16, 'Electronic - Jungle'), (17, 'Trance - Acid'), (18, 'Electronic - IDM'), (19, 'Electronic - Progressive'), (20, 'Electronic - Gabber'), (21, 'Electronic - Minimal'), (22, 'Trance - Hard'), (23, 'Trance - Progressive'), (24, 'Trance - Tribal'), (25, 'Chiptune'), (26, 'Demostyle'), (27, 'One-Hour Compo'), (28, 'Pop - General'), (29, 'Pop - Synth'), (30, 'Pop - Soft'), (31, 'Rock - General'), (32, 'Rock - Soft'), (33, 'Rock - Hard'), (34, 'Funk'), (35, 'Disco'), (36, 'Ballad'), (37, 'Easy Listening'), (38, 'Video Game'), (39, 'Orchestral'), (40, 'Classical'), (41, 'Piano'), (42, 'Fantasy'), (43, 'Soundtrack'), (44, 'Comedy'), (45, 'Medieval'), (46, 'Spiritual'), (47, 'Religious'), (48, 'Experimental'), (49, 'New Age'), (50, 'Folk'), (51, 'Country'), (52, 'Bluegrass'), (53, 'World'), (54, 'Fusion'), (55, 'Vocal Montage'), (56, 'Other'), (57, 'Alternative'), (58, 'Gothic'), (59, 'Punk'), (60, 'Metal - General'), (61, 'Metal - Extreme'), (62, 'Grunge'), (63, 'Jazz - General'), (64, 'Jazz - Modern'), (65, 'Jazz - Acid'), (66, 'Blues'), (67, 'Swing'), (68, 'Big Band'), (69, 'Hip-Hop'), (70, 'Reggae'), (71, 'R&B'), (72, 'Soul'), (73, 'Ska'), (74, 'Christmas'), (75, 'Halloween')], db_index=True, null=True),
        ),
    ]
