# Generated by Django 4.0.1 on 2022-12-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0026_delete_genre_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='pattern_hash',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
