# Generated by Django 4.0.1 on 2023-03-30 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0031_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistcomment',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='song',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
