# Generated by Django 4.0.1 on 2023-04-20 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_profile_create_date'),
        ('songs', '0033_newsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsong',
            name='uploader_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.profile'),
        ),
    ]
