# Generated by Django 4.0.1 on 2023-04-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_profile_create_date'),
        ('songs', '0034_alter_newsong_uploader_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.profile'),
        ),
        migrations.AddField(
            model_name='song',
            name='featured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='is_featured',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
