# Generated by Django 4.0.1 on 2023-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0035_song_featured_by_song_featured_date_song_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='songstats',
            name='total_favorites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
