# Generated by Django 4.0.1 on 2023-07-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0036_songstats_total_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsong',
            options={'permissions': (('can_approve_songs', 'Can approve songs'),)},
        ),
    ]
