# Generated by Django 4.0.1 on 2024-01-12 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_profile_create_date'),
        ('songs', '0037_alter_newsong_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsong',
            name='claim_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsong',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_by', to='homepage.profile'),
        ),
    ]
