# Generated by Django 4.0.1 on 2024-01-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0038_newsong_claim_date_newsong_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsong',
            name='flag',
            field=models.CharField(blank=True, choices=[('pre-screened', 'Pre-screened')], max_length=16),
        ),
    ]
