# Generated by Django 4.0.1 on 2024-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0039_newsong_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsong',
            name='flag',
            field=models.CharField(blank=True, choices=[('pre-screened', 'Pre-screened')], max_length=16, null=True),
        ),
    ]
