# Generated by Django 4.0.1 on 2024-01-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0040_alter_newsong_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsong',
            name='flag',
            field=models.CharField(blank=True, choices=[('pre-screened', 'Pre-screened'), ('pre-screened+', 'Pre-screened and recommend featured'), ('needs-second-opinion', 'Needs second opinion')], max_length=32, null=True),
        ),
    ]
