# Generated by Django 4.0.1 on 2024-01-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_profile_create_date'),
        ('songs', '0041_alter_newsong_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsong',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_by', to='homepage.profile'),
        ),
    ]
