# Generated by Django 4.0.1 on 2024-01-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0042_newsong_flagged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsong',
            name='filename_unzipped',
            field=models.CharField(default='placeholder', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsong',
            name='flag',
            field=models.CharField(blank=True, choices=[('pre-screened', 'Pre-screened'), ('pre-screened+', 'Pre-screened and recommend featured'), ('needs-second-opinion', 'Needs second opinion'), ('possible-duplicate', 'Possible duplicate'), ('under-investigation', 'Under investigation (do not approve)')], max_length=32, null=True),
        ),
    ]
