# Generated by Django 4.0.1 on 2024-01-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0043_newsong_filename_unzipped_alter_newsong_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='filename_unzipped',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='song',
            name='folder',
            field=models.CharField(default='A', max_length=4),
            preserve_default=False,
        ),
    ]
