# Generated by Django 5.0.1 on 2024-01-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_profile_create_date'),
        ('songs', '0044_song_filename_unzipped_song_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_by', to='homepage.profile'),
        ),
        migrations.AlterField(
            model_name='song',
            name='featured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_by', to='homepage.profile'),
        ),
    ]
