# Generated by Django 5.0.1 on 2024-01-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0046_rejectedsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedsong',
            name='format',
            field=models.CharField(blank=True, choices=[('669', '669: Composer 669 / UNIS 669'), ('AHX', "AHX: Abyss' Highest eXperience, formerly THX"), ('AMF', 'AMF: ASYLUM / DSMI'), ('AMS', "AMS: Extreme's Tracker / Velvet Studio"), ('C67', 'C67: CDFM / Composer 670'), ('DBM', 'DBM: Digi Booster Pro'), ('DIGI', 'DIGI: Digi Booster'), ('DMF', 'DMF: X-Tracker'), ('DSM', 'DSM: DSIK'), ('DSYM', 'DSYM: Digital Symphony'), ('DTM', 'DTM: Digital Tracker / Digital Home Studio'), ('FAR', 'FAR: Farandole Composer'), ('FMT', 'FMT: FM Tracker'), ('GDM', 'GDM: BWSB Sound System'), ('HVL', 'HVL: HivelyTracker'), ('IMF', 'IMF: Imago Orpheus'), ('IT', 'IT: Impulse Tracker'), ('J2B', 'J2B: Galaxy Sound System'), ('MED', 'MED: Octamed'), ('MDL', 'MDL: Digitrakker'), ('MO3', 'MO3: Compressed Module'), ('MOD', 'MOD: Protracker, Generic MOD'), ('MPTM', 'MPTM: OpenMPT'), ('MT2', 'MT2: MadTracker 2'), ('MTM', 'MTM: Multi Tracker'), ('OKT', 'OKT: Oktalyzer'), ('PLM', 'PLM: Disorder Tracker 2'), ('PSM', 'PSM: Epic MegaGames MASI'), ('PTM', 'PTM: PolyTracker'), ('S3M', 'S3M: Scream Tracker 3'), ('SFX', 'SFX: SoundFX / MultiMedia Sound'), ('STM', 'STM: Scream Tracker'), ('STP', 'STP: SoundTracker Pro II'), ('STX', 'STX: Scream Tracker Music Interface Kit'), ('SymMOD', 'SymMOD: Symphonie / Symphonie Pro'), ('ULT', 'ULT: UltraTracker'), ('UMX', 'UMX: Unreal Music'), ('XM', 'XM: FastTracker 2')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='rejectedsong',
            name='reason',
            field=models.CharField(choices=[('corrupted', 'Corrupted'), ('poor-quality', 'Poor quality'), ('unsupported-format', 'Unsupported format'), ('custom-message', 'Custom message'), ('midi-conversion', 'MIDI conversion'), ('test-upload', 'Test upload'), ('dispute', 'Dispute'), ('too-short', 'Too short'), ('dubious-content', 'Dubious content'), ('already-exists', 'Already exists'), ('too-big', 'Too big'), ('no-reason-given', 'No reason given'), ('rename-required', 'Rename required'), ('incorrect-file-extension', 'Incorrect file extension'), ('tuning-issues', 'Tuning issues'), ('plagiarism', 'Plagiarism'), ('unknown', 'Unknown'), ('other', 'Other')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='rejectedsong',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
