# Generated by Django 5.0.1 on 2024-02-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0047_alter_rejectedsong_format_alter_rejectedsong_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedsong',
            name='reason',
            field=models.CharField(choices=[('poor-quality', 'Poor quality'), ('already-exists', 'Already exists'), ('too-short', 'Too short'), ('rename-required', 'Rename required'), ('incorrect-file-extension', 'Incorrect file extension'), ('plagiarism', 'Plagiarism'), ('corrupted', 'Corrupted'), ('unsupported-format', 'Unsupported format'), ('custom-message', 'Custom message'), ('test-upload', 'Test upload'), ('dispute', 'Dispute'), ('dubious-content', 'Dubious content'), ('too-big', 'Too big'), ('no-reason-given', 'No reason given'), ('tuning-issues', 'Tuning issues'), ('midi-conversion', 'MIDI conversion'), ('unknown', 'Unknown'), ('other', 'Other')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='SongRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_old_song_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('old_song_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'verbose_name_plural': 'song redirects',
            },
        ),
    ]
