# Generated by Django 5.1.6 on 2025-06-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0048_alter_rejectedsong_reason_songredirect'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='NewSong'),
                migrations.DeleteModel(name='RejectedSong'),
            ]
        )
    ]
