# Generated by Django 5.1.6 on 2025-06-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0049_remove_rejectedsong_rejected_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='song',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='song',
        ),
        migrations.DeleteModel(
            name='ArtistComment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
