# Generated by Django 5.1.6 on 2025-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0050_remove_comment_profile_remove_comment_song_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='clean_title',
        ),
        migrations.AddField(
            model_name='song',
            name='title_from_file',
            field=models.CharField(default='unknown', max_length=120),
        ),
    ]
