# Generated by Django 5.1.6 on 2025-07-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0051_remove_song_clean_title_song_title_from_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title_from_file',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
