# Generated by Django 5.1.6 on 2026-02-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0052_alter_song_title_from_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songstats',
            name='average_comment_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='songstats',
            name='average_review_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
    ]
