# Generated by Django 5.1.6 on 2026-07-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0053_alter_songstats_average_comment_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='search_document',
        ),
    ]
