# Generated by Django 5.1.6 on 2026-07-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0054_remove_song_search_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='average_comment_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='comments_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
