# Generated by Django 5.1.6 on 2026-07-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0055_song_average_comment_score_song_comments_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='average_comment_score',
            new_name='average_rating',
        ),
    ]
