# Generated by Django 5.1.6 on 2026-07-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0056_rename_average_comment_score_song_average_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongStats',
        ),
    ]
