# Generated by Django 5.1.6 on 2026-07-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0057_delete_songstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cumulative_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
