# Generated by Django 5.1.6 on 2026-07-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0058_song_cumulative_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cumulative_rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
