# Generated by Django 3.2.9 on 2021-12-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklisteddomain',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
