# Generated by Django 3.2.9 on 2021-12-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_blacklisteddomain_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisteddomain',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
