# Generated by Django 4.0.1 on 2022-04-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='legacy_id',
            field=models.IntegerField(null=True),
        ),
    ]
