# Generated by Django 4.0.1 on 2022-05-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_profile_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blurb',
            field=models.TextField(blank=True, max_length=24000, null=True),
        ),
    ]
