# Generated by Django 4.0.1 on 2022-08-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news_items'},
        ),
    ]
