# Generated by Django 4.0.1 on 2022-12-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_news_create_date_news_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='legacy_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
