# Generated by Django 5.1.6 on 2025-10-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_profile_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enable_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='enable_shoutwall',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='enable_shoutwall_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
