# Generated by Django 5.1.6 on 2025-10-27 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisteddomain',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
