# Generated by Django 5.1.6 on 2025-10-31 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_alter_message_create_date_alter_message_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_starter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_replies', to='homepage.message'),
        ),
    ]
