# Generated by Django 4.0.1 on 2022-01-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_legacy_id'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(to='songs.Song'),
        ),
    ]
