# Generated by Django 4.0.1 on 2022-02-17 04:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='artists_art_search__e59b10_gin'),
        ),
    ]
