# Generated by Django 4.0.1 on 2022-05-24 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_profile_legacy_id'),
        ('artists', '0004_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.profile'),
        ),
    ]
