# Generated by Django 4.0.1 on 2022-06-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
