# Generated by Django 4.0.1 on 2022-06-03 13:54

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_alter_artist_name'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=64, unique=True),
        ),
    ]
