# Generated by Django 4.0.1 on 2022-06-10 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0006_alter_profile_blurb'),
        ('songs', '0007_remove_song_hits_alter_songstats_downloads'),
        ('artists', '0007_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='artist',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.profile'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='songs.Song'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
