# Generated by Django 4.0.1 on 2022-12-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_alter_artist_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='User ID from the legacy Mod Archive site', null=True),
        ),
    ]
