# Generated by Django 4.0.1 on 2023-03-30 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_alter_artist_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
