# Generated by Django 5.0.1 on 2024-01-23 17:06

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_alter_artist_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='random_token',
            field=models.PositiveIntegerField(blank=True, help_text='Used for differentiating artists with the same name', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('name', 'random_token')},
        ),
    ]
