# Generated by Django 5.1.6 on 2025-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_artist_random_token_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
