# Generated by Django 5.1.6 on 2025-07-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_alter_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
    ]
