# Generated by Django 5.1.6 on 2025-07-26 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_remove_artist_songs'),
        ('songs', '0050_remove_comment_profile_remove_comment_song_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'unique_together': {('artist', 'song')},
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(blank=True, through='artists.ArtistSong', to='songs.song'),
        ),
    ]
