# Generated by Django 5.1.6 on 2026-05-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_artistsong_artist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='average_song_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='total_comments',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='total_downloads',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='total_songs',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
