# Generated by Django 5.1.6 on 2026-07-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0016_artist_average_song_rating_artist_total_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cumulative_ratings',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
