# Generated by Django 5.1.6 on 2026-07-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0017_artist_cumulative_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='cumulative_ratings',
            new_name='cumulative_song_ratings',
        ),
    ]
