# Generated by Django 5.1.6 on 2026-07-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0018_rename_cumulative_ratings_artist_cumulative_song_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='average_song_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
    ]
