CLAIM_KEYWORD = 'claim'
CLAIM_DESCRIPTION = 'Claim Songs for Screening'
CLAIM_ACTION = (CLAIM_KEYWORD, CLAIM_DESCRIPTION)

PRE_SCREEN_KEYWORD = 'pre_screen'
PRE_SCREEN_DESCRIPTION = 'Pre-Screen Songs'
PRE_SCREEN_ACTION = (PRE_SCREEN_KEYWORD, PRE_SCREEN_DESCRIPTION)

PRE_SCREEN_AND_RECOMMEND_KEYWORD = 'pre_screen_and_recommend'
PRE_SCREEN_AND_RECOMMEND_DESCRIPTION = 'Pre-Screen Songs and Recommend for Featured'
PRE_SCREEN_AND_RECOMMEND_ACTION = (PRE_SCREEN_AND_RECOMMEND_KEYWORD, PRE_SCREEN_AND_RECOMMEND_DESCRIPTION)

HIGH_PRIORITY_FILTER = 'high_priority'
HIGH_PRIORITY_FILTER_DESCRIPTION = 'High Priority'
LOW_PRIORITY_FILTER = 'low_priority'
LOW_PRIORITY_FILTER_DESCRIPTION = 'Low Priority'
BY_UPLOADER_FILTER = 'by_uploader'
BY_UPLOADER_FILTER_DESCRIPTION = 'Uploaded by Artist'
MY_SCREENING_FILTER = 'my_screening'
MY_SCREENING_FILTER_DESCRIPTION = 'Songs I\'m Screening'
OTHERS_SCREENING_FILTER = 'others_screening'
OTHERS_SCREENING_FILTER_DESCRIPTION = 'Songs Others are Screening'
PRE_SCREENED_FILTER = 'pre_screened'
PRE_SCREENED_FILTER_DESCRIPTION = 'Pre-Screened'
PRE_SCREENED_AND_RECOMMENDED_FILTER = 'pre_screened_and_recommended'
PRE_SCREENED_AND_RECOMMENDED_FILTER_DESCRIPTION = 'Pre-Screened and Recommended'
