CLAIM_KEYWORD = 'claim'
CLAIM_DESCRIPTION = 'Claim Songs for Screening'
CLAIM_ACTION = (CLAIM_KEYWORD, CLAIM_DESCRIPTION)

PRE_SCREEN_KEYWORD = 'pre_screen'
PRE_SCREEN_DESCRIPTION = 'Pre-Screen Songs'
PRE_SCREEN_ACTION = (PRE_SCREEN_KEYWORD, PRE_SCREEN_DESCRIPTION)

PRE_SCREEN_AND_RECOMMEND_KEYWORD = 'pre_screen_and_recommend'
PRE_SCREEN_AND_RECOMMEND_DESCRIPTION = 'Pre-Screen Songs and Recommend for Featured'
PRE_SCREEN_AND_RECOMMEND_ACTION = (PRE_SCREEN_AND_RECOMMEND_KEYWORD, PRE_SCREEN_AND_RECOMMEND_DESCRIPTION)

NEEDS_SECOND_OPINION_KEYWORD = 'needs_second_opinion'
NEEDS_SECOND_OPINION_DESCRIPTION = 'Apply Flag: Needs Second Opinion'
NEEDS_SECOND_OPINION_ACTION = (NEEDS_SECOND_OPINION_KEYWORD, NEEDS_SECOND_OPINION_DESCRIPTION)

POSSIBLE_DUPLICATE_KEYWORD = 'possible_duplicate'
POSSIBLE_DUPLICATE_DESCRIPTION = 'Apply Flag: Possible Duplicate'
POSSIBLE_DUPLICATE_ACTION = (POSSIBLE_DUPLICATE_KEYWORD, POSSIBLE_DUPLICATE_DESCRIPTION)

UNDER_INVESTIGATION_KEYWORD = 'under_investigation'
UNDER_INVESTIGATION_DESCRIPTION = 'Apply Flag: Under Investigation'
UNDER_INVESTIGATION_ACTION = (UNDER_INVESTIGATION_KEYWORD, UNDER_INVESTIGATION_DESCRIPTION)

UNCLAIMED_GROUP = 'Unclaimed'
CLAIMED_GROUP = 'Claimed'
DONE_GROUP = 'Done'
FLAGGED_GROUP = 'Flagged'
HIGH_PRIORITY_FILTER = 'high_priority'
HIGH_PRIORITY_FILTER_DESCRIPTION = 'High Priority'
LOW_PRIORITY_FILTER = 'low_priority'
LOW_PRIORITY_FILTER_DESCRIPTION = 'Low Priority'
BY_UPLOADER_FILTER = 'by_uploader'
BY_UPLOADER_FILTER_DESCRIPTION = 'Uploaded by Artist'
MY_SCREENING_FILTER = 'my_screening'
MY_SCREENING_FILTER_DESCRIPTION = 'Songs I\'m Screening'
OTHERS_SCREENING_FILTER = 'others_screening'
OTHERS_SCREENING_FILTER_DESCRIPTION = 'Songs Others are Screening'
PRE_SCREENED_FILTER = 'pre_screened'
PRE_SCREENED_FILTER_DESCRIPTION = 'Pre-Screened'
PRE_SCREENED_AND_RECOMMENDED_FILTER = 'pre_screened_and_recommended'
PRE_SCREENED_AND_RECOMMENDED_FILTER_DESCRIPTION = 'Pre-Screened and Recommended'
NEEDS_SECOND_OPINION_FILTER = 'needs_second_opinion'
NEEDS_SECOND_OPINION_FILTER_DESCRIPTION = 'Needs Second Opinion'
POSSIBLE_DUPLICATE_FILTER = 'possible_duplicate'
POSSIBLE_DUPLICATE_FILTER_DESCRIPTION = 'Possible Duplicate'
UNDER_INVESTIGATION_FILTER = 'under_investigation'
UNDER_INVESTIGATION_FILTER_DESCRIPTION = 'Under Investigation (do not approve)'
