# Generated by Django 5.1.6 on 2025-06-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsong',
            table='uploads_newsong',
        ),
        migrations.AlterModelTable(
            name='rejectedsong',
            table='uploads_rejectedsong',
        ),
    ]
