# Generated by Django 5.1.6 on 2025-06-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_newsong_table_alter_rejectedsong_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsong',
            options={'permissions': (('can_approve_songs', 'Can approve songs'), ('can_upload_songs', 'Can upload songs'))},
        ),
    ]
