# Generated by Django 5.1.6 on 2025-06-28 04:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_profile_create_date'),
        ('uploads', '0003_alter_newsong_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('claim', 'Claim'), ('unclaim', 'Unclaim'), ('apply_tag', 'Apply Tag'), ('clear_tag', 'Clear Tag'), ('rename', 'Rename')], max_length=32)),
                ('content', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_events', to='uploads.newsong')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_events', to='homepage.profile')),
            ],
            options={
                'db_table': 'uploads_screening_event',
            },
        ),
    ]
