# Generated by Django 5.1.6 on 2025-07-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_screeningevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningevent',
            name='type',
            field=models.CharField(choices=[('claim', 'Claim'), ('unclaim', 'Unclaim'), ('apply_flag', 'Apply Flag'), ('clear_flag', 'Clear Flag'), ('rename', 'Rename')], max_length=32),
        ),
    ]
